name: Build and Deploy Spring App Book Social Network

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and deploy SpringBoot Book Social Network
    runs-on: ubuntu-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
