name: Build and Deploy Spring App Book Social Network

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Set Docker tag
        id: docker_tag
        run: echo "::set-output name=tag::$(echo ${{ secrets.DOCKER_HUB_USERNAME }}/book-social-network:latest | tr '[:upper:]' '[:lower:]')"

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.docker_tag.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
